# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8321eb4bb105ba49cb4555a6f4b22258cec489d3fb89dc944462cfee19f88776f81da9e69c7c905af49a0f59d2158dd7c1efd190cddca4367b770f123297328b

test:
  secret_key_base: c7313d081a5e1d92ee69d55b12ffb9ac959e9478e440bf566be3dc03574e5b925b568f8711fd42a47460cefabc54485ed6cf533c44f3e9fbfbdd7bc532de5dcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
